config/routes.rb
WebStringer::Application.routes.draw do
  resources :tennis_strings do
    member do
      get 'users_of'
      post 'update_data'
    end

    collection do
      get 'tree_view'
      get 'tennis_strings_for_combo'
      get 'load_manufacturers'
      get 'all_for_manufacturer'
    end
  end

  resources :racket_stringings do
    collection do
      get 'queue'
      get 'accounts_receivable'
    end
  end

  resources :customers do
    collection do
      get 'load_customer_rackets'
    end
  end

  resources :accounts_receivable

  resources :web_stringer

  resources :metrics

  resources :customer_filters

  resources :companies

  resources :grip_sizes

  resources :customer_rackets do
    member do
      post 'update_customer_racket_notes'
    end
    collection do
      get 'queue'
    end
  end

  resources :string_constructions

  resources :string_manufacturers

  resources :racket_manufacturers

  resources :admin do
    collection do
      get 'login'
    end
  end

  resources :users do
    collection do
      get 'tree_view'
      post 'login'
    end
  end

  resources :string_patterns

  resources :rackets do
    member do
      get 'users_of'
      post 'update_data'
    end

    collection do
      get 'tree_view'
      get 'load_racket_details'
      get 'load_manufacturers'
      get 'all_for_manufacturer'
    end
  end

  root :to => "customers#index"

end

app/models/customer_racket.rb
class CustomerRacket < ActiveRecord::Base
  has_many :racket_stringings, :order => 'strung_on DESC', :dependent => :destroy
  belongs_to :racket
  belongs_to :customer
  belongs_to :grip_size

  scope :authorized, lambda {
    includes(:customer).where("customers.user_id = ?", (User.current.id rescue -1))
  }

  class << self
    alias_method :old_find, :find
    def find(*args)
      options = args.extract_options!
      conditions = options[:conditions]
      if (conditions.nil?)
        options[:conditions] = ['customers.user_id = ?', (User.current.id rescue -1)]
      else
        if conditions.class == Array
          conditions[0] = "#{conditions[0]} AND customers.user_id = ?"
          conditions << (User.current.id rescue -1)
        else
          conditions = "#{conditions} AND customers.user_id = #{(User.current.id rescue -1)}"
        end
        options[:conditions] = conditions
      end

      includes = options[:include]
      if includes.nil?
        options[:include] = [:customer]
      else
        if includes.class == Array
          includes << :customer
          includes = includes.flatten.uniq
        else
          includes = [includes, :customer].flatten.uniq
        end
        options[:include] = includes
      end

      args << options
      old_find(*args)
    end
  end

  def current_bill
    total_owed = 0
    racket_stringings.each do |racket_stringing|
      total_owed += racket_stringing.cost unless racket_stringing.payment_received?
    end
    total_owed
  end

  def customers
    [ self.customer.as_json ]
  end

  def rackets
    [ self.racket ]
  end

  def tree_id
    "racket_#{self.id}"
  end

  def grip
    self.grip_size.to_s
  end

  def as_tree_node
    customerJson = "{\n\t\"name\": \"#{racket.racket_manufacturer.name} #{racket.model}\""
    customerJson += ",\n\t\"id\": #{id}"
    customerJson += ",\n\t\"tree_id\": \"racket_#{id}\""
    customerJson += ",\n\t\"leaf\": true"
    customerJson += ",\n\t\"iconCls\": \"racquet-icon\""
    customerJson += ",\n\t\"customer_id\": #{customer.id}"
    customerJson += ",\n\t\"lastStrungOn\": \"#{racket_stringings.first.strung_on}\"" if racket_stringings.first
    customerJson += ",\n\t\"current_bill\": #{current_bill}"
    customerJson += "\n\t}"
  end

  def get_json
    ActiveRecord::Base.include_root_in_json = false
    self.to_json(:methods => [:rackets, :grip], :include => { :racket_stringings => { :methods => [:string_name, :tension] } } )
  end

  def as_json(options = {})
    super(:include => {:racket_stringings => {:methods => [:string_name, :tension, :strung_by] }}, :methods => [:customers, :rackets, :grip] )
  end
end

app/controllers/customer_rackets_controller.rb
class CustomerRacketsController < ApplicationController

  def new
    @customer_racket = CustomerRacket.new(:customer => Customer.find(params[:customer_id]))
  end

  def show
    @customer_racket = CustomerRacket.find(params[:id]);
    respond_to do |format|
      format.json { render :json => @customer_racket.get_json }
    end
  end

  def destroy
    begin
        CustomerRacket.find(params[:id]).delete;
        render :json => "{ success: true }"
    rescue => e
      render :json => "{ success: false }"
    end
  end

  def create
    @customer_racket = CustomerRacket.create(params[:customer_racket])
    if @customer_racket.save
      render :json => "{ success: true, url: '#{customer_racket_path(@customer_racket)}.json', customer_racquet: #{@customer_racket.as_tree_node} }"
    else
      render :json => "{ success: false }"
    end
  end

  def update_racket_models
    racket_manufacturer = RacketManufacturer.find(params[:racket_manufacturer_id])
    @racket_models = Racket.find_all_by_racket_manufacturer_id(racket_manufacturer)
  end

  def update_racket_model_details
    @racket = Racket.find(params[:racket_id])
  end

  def edit
    params[:page] ||= 1
    params[:per_page] ||= 10
    @customer_racket = CustomerRacket.find(params[:id])
    @racket_stringings = @customer_racket.racket_stringings.paginate(:page => params[:page], :per_page => params[:per_page])
  end

  def update_strung_on
    racket_stringing = RacketStringing.find(params[:id])
    if params[:strung_on] == "true"
      racket_stringing.strung_on = Time.now
    else
      racket_stringing.strung_on = nil
    end
    racket_stringing.save
    
    if params[:notify] == "true"
      CustomerMailer.deliver(CustomerMailer.create_racket_completed(racket_stringing))
    end
  end

  def update_payment_received
    racket_stringing = RacketStringing.find(params[:id])
    racket_stringing.payment_received = params[:payment_received]
    racket_stringing.save
  end

  def update_customer_racket_notes
    @customer_racket = CustomerRacket.find(params[:id])
    @customer_racket.notes = params[:customer_racket_notes]
    @customer_racket.save
    respond_to do |format|
      format.json { render :json => @customer_racket.get_json }
    end
  end

  def get_rackets_by_manufacturer
    @racket_manufacturer = RacketManufacturer.find(params[:racket_manufacturer_id])
    @racket = Racket.all_for_manufacturer(@racket_manufacturer).first
  end

  def get_racket_image
    @racket = Racket.find(params[:racket_id])
  end

  def new_stringing
    @customer_racket = CustomerRacket.find(params[:id])
    params[:racket_stringing] = {:dropped_off => params[:dropped_off]}
    if params[:is_two_piece]
      params[:racket_stringing][:is_two_piece] = true
      params[:racket_stringing][:main_string] = TennisString.find(params[:main_string])
      params[:racket_stringing][:main_tension] = params[:main_tension]
      params[:racket_stringing][:cross_string] = TennisString.find(params[:cross_string])
      params[:racket_stringing][:cross_tension] = params[:cross_tension]
    else
      params[:racket_stringing][:is_two_piece] = false
      params[:racket_stringing][:main_string] = TennisString.find(params[:main_string])
      params[:racket_stringing][:main_tension] = params[:main_tension]
    end
    params[:racket_stringing][:cost] = params[:cost]
    params[:racket_stringing][:requested_by] = params[:requested_by] unless params[:requested_by].empty?
    params[:racket_stringing][:strung_on] = params[:strung_on] unless params[:strung_on].empty?
    racket_stringing = RacketStringing.create(params[:racket_stringing])
    @customer_racket.racket_stringings << racket_stringing if racket_stringing.errors.empty?
    @customer_racket.save

    params[:page] ||= 1
    params[:per_page] ||= 10
    @racket_stringings = @customer_racket.racket_stringings.paginate(:page => params[:page], :per_page => params[:per_page])
  end
end

app/helpers/customer_rackets_helper.rb
module CustomerRacketsHelper
end

app/views/customer_rackets/_edit_racket_image.html.erb
<div id='editRacketImageDiv'>
  <%= image_tag racket.image.url(:medium) %>
</div>

app/views/customer_rackets/_racket_details.html.erb
<div id='customerRacketDetails'>
  <table width='100%'>
    <thead>
      <th colspan=2>Specifications</th>
      <th style='text-align: center'>Image</th>
    </thead>
    <tr>
      <td>Manufacturer:</td>
      <td><%= racket.racket_manufacturer.name rescue "" %></td>
      <td style='padding-left: 15px' rowspan=5><%= (image_tag(racket.image.url(:small)) rescue "") %></td>
    </tr>
    <tr>
      <td style='padding-top: 5px'>Model:</td>
      <td style='padding-top: 5px'><%= racket.model rescue "" %></td>
    </tr>
    <tr>
      <td style='padding-top: 5px'>String Pattern:</td>
      <td style='padding-top: 5px'><%= racket.string_pattern.name rescue "" %></td>
    </tr>
    <tr>
      <td style='padding-top: 5px'>Head Size:</td>
      <td style='padding-top: 5px'><%= racket.head_size rescue "" %></td>
    </tr>
  </table>

</div>

app/views/customer_rackets/_racket_model_options.html.erb
<div id='customerRacketModelOptions'>
  <%= select_tag :racket_model,
                 options_from_collection_for_select(Racket.all_for_manufacturer(racket.racket_manufacturer), :id, :model, racket.id),
                 :onchange => 'updateRacketModelImage(this)'%>
</div>

app/views/customer_rackets/_racket_models.html.erb
<div id='customerRacketModels'>
  <%= select_tag :racket_id,
                 options_from_collection_for_select([Racket.new(:model => 'Select', :id => -1)].concat(racket_models), :id, :full_name),
                 :onchange => 'updateRacketModelDetails(this)'%>
</div>

app/views/customer_rackets/edit.html.erb
<% javascript_tag do %>
  Ext.onReady(function(){

    _mainContentPanel.add(new Ext.Panel({
      layout: 'border',
      border: false,
      items: [
        new Ext.Panel({
          region: 'west',
          title: 'Racket',
          split: true,
          width: 470,
          layout: 'fit',
          margins: '0, 0, 0, 0',
          items: new Ext.Panel({
            // xtype: 'panel' implied by default
            contentEl: 'westDiv',
            id: 'west-region-container',
          width: 450,
          minSize: 450,
          autoScroll: true,
            layout: 'fit',
            margins: '20',
            unstyled: true,
            border: true
          })
        }), new Ext.Panel({
          region: 'center',     // center region is required, no width/height specified
          xtype: 'container',
          layout: 'border',
          autoscroll: true,
          minSize: 500,
          margins: '0, 0, 0, 0',
          items: {
            region: 'center',
            contentEl: 'centerDiv',
            border: false
          }
        })
      ]
    }));
    _mainContentPanel.doLayout({force: true});
  });

  function updateRacketModels(list) {
    var params = new Hash();
    params.set('racket_manufacturer_id', list.options[list.selectedIndex].value);
    new Ajax.Request("/customer_rackets/get_rackets_by_manufacturer", { asynchronous:true, evalScripts:true, parameters: params });
  }

  function updateRacketModelImage(list) {
    var params = new Hash();
    params.set('racket_id', list.options[list.selectedIndex].value);
    new Ajax.Request("/customer_rackets/get_racket_image", { asynchronous:true, evalScripts:true, parameters: params });
  }
<% end %>

<style>
  table.racketSpecTable tr td {
    padding-top: 2px;
    padding-bottom: 2px;
  }
</style>

<div id='westDiv' style='padding-left: 10px; padding-right: 10px'>
  <% form_for @customer_racket do |f| %>
    <% is_two_piece = (@customer_racket.racket_stringings.first.is_two_piece? rescue nil) %>
    <table width='450px' class='racketSpecTable'>
      <thead>
        <th colspan=2 style='text-align: center'>Specifications</th>
        <th/>
      </thead>
      <tr>
        <td>Make:</td>
        <td>
          <%= select_tag :racket_manufacturer,
                         options_from_collection_for_select(RacketManufacturer.all(:order => 'name'), :id, :name, @customer_racket.racket.racket_manufacturer.id),
                         :onchange => 'updateRacketModels(this)'%>
        </td>
        <td rowspan=<%= is_two_piece ? "11" : "9" %> style='text-align: right'>
          <%= render :partial => 'edit_racket_image', :locals => { :racket => @customer_racket.racket } %>
        </td>
        
      </tr>
      <tr>
        <td>Model:</td>
        <td>
          <%= render :partial => 'racket_model_options',
                     :locals => { :racket => @customer_racket.racket } %>
        </td>
      </tr>
      <tr>
        <td>String Pattern:</td>
        <td><%= "#{@customer_racket.racket.string_pattern.mains} x #{@customer_racket.racket.string_pattern.crosses}" %></td>
      </tr>
      <tr>
        <td>Head Size:</td>
        <td><%= "#{@customer_racket.racket.head_size} sqin" %></td>
      </tr>
      <tr>
        <td>Grip Size:</td>
        <td><%= @customer_racket.grip_size.size %></td>
      </tr>
      <tr>
        <td>Last Strung:</td>
        <td><%= (@customer_racket.racket_stringings.first.strung_on.to_s(:standard) rescue "N/A") %></td>
      </tr>
      <tr>
        <td>Pieces:</td>
        <td><%= (is_two_piece.nil? ? "N/A" : (is_two_piece ? "2" : "1")) %></td>
      </tr>
      <tr>
        <% tennis_string = (@customer_racket.racket_stringings.first.main_string rescue nil) %>
        <td><%= is_two_piece ? "Main " : "" %><%= "String:" %></td>
        <td><%= ("#{tennis_string.string_manufacturer.name} #{tennis_string.name}" rescue "N/A") %></td>
      </tr>
      <tr>
        <td><%= is_two_piece ? "Main " : "" %><%= "Tension:" %></td>
      <td><%= (@customer_racket.racket_stringings.first.main_tension rescue "N/A") %></td>
      </tr>
      <% if is_two_piece %>
        <tr>
          <% tennis_string = (@customer_racket.racket_stringings.first.cross_string rescue nil) %>
          <td><%= "Cross String:" %></td>
          <td><%= ("#{tennis_string.string_manufacturer.name} #{tennis_string.name}" rescue "N/A") %></td>
        </tr>
        <tr>
          <td><%= "Cross Tension:" %></td>
          <td><%= (@customer_racket.racket_stringings.first.cross_tension rescue "N/A") %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <div style='padding-top: 5px'>
    <% form_remote_tag :url => { :action => 'update_customer_racket_notes' },
                       :before => "tinyMCE.triggerSave(true,true)" do %>
      <%= hidden_field_tag :id, @customer_racket.id %>
      <%= "Racket Notes:" %>
      <%= text_area_tag :customer_racket_notes, @customer_racket.notes, :class => 'mceEditor' %>
      <div style='padding-top: 5px'><%= submit_tag "Update" %></div>
    <% end %>
  </div>
</div>

<div id='centerDiv'>

  <div style='padding: 20px'>
    <%= render :partial => "new_stringing" %>
  </div>
  <div style='padding: 20px'>
    <%= render :partial => "stringing_history", :locals => { :racket_stringings => @racket_stringings } %>
  </div>
</div>

app/views/customer_rackets/new.html.erb
<% javascript_tag do %>
  Ext.onReady(function(){

    _mainContentPanel.add(new Ext.Panel({
      layout: 'border',
      title: 'Customers',
      autoscroll: true,
      border: false,
      items: [
        new Ext.Panel({
          region: 'center',     // center region is required, no width/height specified
          xtype: 'container',
          layout: 'border',
          autoscroll: true,
          minSize: 500,
          margins: '0, 0, 0, 0',
          items: {
            region: 'center',
            contentEl: 'centerDiv',
            border: false
          }
        })
      ]
    }));
    _mainContentPanel.doLayout({force: true});
  });

  function updateRacketModels(list) {
    var params = new Hash();
    params.set("racket_manufacturer_id", list.options[list.selectedIndex].value);
    new Ajax.Request("/customer_rackets/update_racket_models",
                     {
                        asynchronous:true,
                        evalScripts:true,
                        parameters: params,
                        onCreate: function() { $('racket_id').disabled = true; },
                        onComplete: function() { $('racket_id').disabled = false; }
                     });
  }

  function updateRacketModelDetails(list) {
    var params = new Hash();
    params.set("racket_id", list.options[list.selectedIndex].value);
    new Ajax.Request("/customer_rackets/update_racket_model_details",
                     {
                        asynchronous:true,
                        evalScripts:true,
                        parameters: params,
                        onCreate: function(transport) { Element.show('updating_model_details_spinner'); },
                        onComplete: function(transport) { Element.hide('updating_model_details_spinner'); }
                     });
  }
<% end %>

<style>
  div.update_racket_model_details_div {
    position: relative;
  }

  div.updating_model_details_spinner {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0.5;
    filter: alpha(opacity=50);
    background: #ddd;
    text-align:center;
  }

  table.customerRacketTable tr td {
    padding-top: 5px;
    padding-bottom: 5px;
  }

</style>

<div id='centerDiv' style='padding-left: 10px; padding-right: 10px'>
  <% form_for @customer_racket do |f| %>
    <%= f.hidden_field :customer_id %>

    <table class='customerRacketTable' width='100%'>
      <tr>
        <td>
          <% field_set_tag "Rackets" do %>
            <table>
              <tr>
                <td>Manufacturer:</td>
                <td><%= select_tag :racket_manufacturer_id,
                                 options_from_collection_for_select(
                                    [RacketManufacturer.new(:name => "Select", :id => -1)].concat(RacketManufacturer.all(:order => 'name')), :id, :name),
                                 :onchange => 'updateRacketModels(this)'   %></td>
              </tr>
              <tr>
                <td>Model:</td>
                <td><%= render :partial => 'racket_models', :locals => {:racket_models => []} %></td>
              </tr>
              <tr>
                <td>Grip Size:</td>
                <td><%= f.select :grip_size_id, options_from_collection_for_select(GripSize.all(:order => :size), :id, :size) %></td>
              </tr>
              <tr>
                <td colspan=2>
                  <div class='update_racket_model_details_div'>
                    <%= render :partial => 'racket_details', :locals => {:racket => nil} %>
                    <div id='updating_model_details_spinner' class='updating_model_details_spinner' style='display: none'>
                      <p><%= image_tag('ajax_loader.gif') %></p>
                    </div>
                  </div>
                </td>
              </tr>
            </table>
            <div>
              <%= f.submit "Add Racket" %>
            </div>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
  <div>
    <%= button_to "Racket not Listed", new_racket_path %>
  </div>
</div>